[package]
description = "List public items (public API) of library crates. Enables diffing public API between releases."
documentation = "https://docs.rs/public_items"
edition = "2021"
homepage = "https://github.com/Enselic/public_items"
license = "MIT"
name = "public_items"
repository = "https://github.com/Enselic/public_items"
version = "0.0.3"

[dependencies]
rustdoc-types = "0.5.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
